In [1]:
import numpy as np

#THE BASICS :

#initialize array
a=np.array([1,2,3],dtype="int16") # with assigning to dtype i,e keyword argument we  can make it possible to store our data in specified number of bytes
#but it need to fit into that specified byte of storage; 
print("one dimensional array :",a)

b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array :",b)


one dimensional array : [1 2 3]
two dimensional array : [[1.  2.  3.  5.8]
 [2.1 3.  4.2 4.5]]


In [3]:
#Get Dimension
print("dimension of a :",a.ndim)
print("dimension of b :",b.ndim)


dimension of a : 1
dimension of b : 2


In [2]:

#Get Shape
print("shape of a :",a.shape) #its a vector so its tellings us one dimension 
print("shape of b :",b.shape)


shape of a : (3,)
shape of b : (2, 4)


In [4]:
#Get  Type
print("a type is :",a.dtype)


a type is : int16


In [5]:
#Get Size
print("size of a :",a.size) # # of element in the array.i,e length of array;

size of a : 3


In [6]:
#total size
print("a item size :",a.itemsize) # size of single element in the array .i,e in bytes;
print("total size is a:",a.size*a.itemsize)


a item size : 2
total size is a: 6


In [7]:
#ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS ETC

#Get specific element [row,column] -ve index is possible similar to list;
b[1,2]

np.float64(4.2)

In [8]:
#Get specific row [row,:]#we use slicing(:) operation
print("row :",b[1,0:1]);

#Get specific column[:,column]
print("column :",b[:,1])

row : [2.1]
column : [2. 3.]


In [9]:
#Getting a little more fancy [starindex:endindex:steps]
print("subset of specific row",b[1,1::2])

subset of specific row [3.  4.5]


In [10]:
#change element
b[1,2]=8
print(b)

b[:,2]=[9,4]
b

[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])